# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: INFO
    io.github.jhipster: INFO
    io.github.jhipster.registry: INFO

spring:
  profiles:
    active: prod
    include:
      - swagger
      - oauth2
      - keycloak
      - zipkin
      # Uncomment to activate TLS for the dev profile
      #- tls
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  mail:
    host: localhost
    port: 25
    username:
    password:
  security:
    user:
      name: admin
      password: admin
      roles: USER, ADMIN
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false
  sleuth:
    sampler:
      probability: 1 # report 100% of traces
  zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
    base-url: http://${ZIPKIN_HOST}:9411
    enabled: true
    locator:
      discovery:
        enabled: true

server:
  port: 8761
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024

# ===================================================================
# Eureka server configuration (eureka.server.*)
#
# Full list of properties with default values at:
# https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaServerConfigBean.java
#
# Documentation at:
# https://github.com/Netflix/eureka/blob/master/eureka-core/src/main/java/com/netflix/eureka/EurekaServerConfig.java
# ===================================================================

eureka:
  client:
    service-url:
      defaultZone: http://admin:${spring.security.user.password}@jhipster-registry:8761/eureka/

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  http:
    cache: # Used by the CachingHttpHeadersFilter
      timeToLiveInDays: 1461
  security:
    client-authorization:
      client-id: internal
      client-secret: internal
    authentication:
      jwt:
        # The secret key should come from a Spring Cloud Config server, and not from this file
        # If using the "native" profile, it should be located in the "central-config" directory
        # If using the "git" profile, it should come from an external Git repository
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail: # specific JHipster mail property, for standard properties see MailProperties
    enabled: false
    from: JHipsterRegistry@localhost
    base-url: http://127.0.0.1:8761
  metrics:
    logs: # Reports metrics in the logs
      enabled: false
      report-frequency: 60 # in seconds
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: true
      host: ${LOGSTASH_HOST}
      port: 5000
      queue-size: 512
# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:
